import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-black text-white">
      <Navbar />
      <div className="flex-1 container mx-auto px-4 py-24">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
          
          <div className="prose prose-invert max-w-none">
            <p className="text-gray-300">Last updated: {new Date().toLocaleDateString()}</p>
            
            <h2>1. Introduction</h2>
            <p>
              Welcome to ContentFlash ("we," "our," or "us"). By accessing or using our website, services, or applications (collectively, the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.
            </p>
            
            <h2>2. Use of the Service</h2>
            <p>
              You agree to use the Service only for lawful purposes and in accordance with these Terms. You are prohibited from using the Service in any way that violates applicable laws or regulations.
            </p>
            
            <h2>3. Account Registration</h2>
            <p>
              To access certain features of the Service, you may be required to register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.
            </p>
            
            <h2>4. Content Generation</h2>
            <p>
              Our Service uses artificial intelligence to generate content. While we strive to provide high-quality content, we do not guarantee that the generated content will be error-free, accurate, or suitable for your specific purposes.
            </p>
            <p>
              You are solely responsible for reviewing and editing any content generated by our Service before publishing or distributing it. You are also responsible for ensuring that the generated content complies with applicable laws, regulations, and platform-specific guidelines.
            </p>
            
            <h2>5. Intellectual Property</h2>
            <p>
              Once content is generated and delivered to you, you own all rights to use that content as you see fit, subject to these Terms. However, we retain all rights to our Service, including our algorithms, software, and technology.
            </p>
            
            <h2>6. Fees and Payment</h2>
            <p>
              Some features of the Service may require payment. You agree to pay all fees in accordance with the pricing posted on our website or otherwise communicated to you.
            </p>
            
            <h2>7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
            
            <h2>8. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. If we make changes, we will provide notice to you by updating the date at the top of these Terms and, in some cases, we may provide additional notice. Your continued use of the Service after the changes have been made will constitute your acceptance of the changes.
            </p>
            
            <h2>9. Termination</h2>
            <p>
              We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms.
            </p>
            
            <h2>10. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions.
            </p>
            
            <h2>11. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at support@contentflash.ai.
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
} 